# Platform specific configurations
platforms:
  yeswehack:
    enabled: true
  hackerone:
    enabled: true
  intigriti:
    enabled: true
    exclusions:
      - "201f8ade-4d93-4d8b-b371-af5ed9d8b837"
  bugcrowd:
    enabled: true
  immunefi:
    enabled: false

# Sync settings
sync:
  auto: true
  delay: 10800 # 3 hours

# History retention (in days)
history_retention_days: 30
